### ISSUE TITLE
capnp-rpc via TLS: authentication?

### ISSUE THREAD

**Issue by hannesm** [mirage/capnp-rpc#126]
If I understand this correctly, the client initiates a TLS connection to the server, and then sends over the capability.  Is the server authenticated (i.e. to avoid a malicious person in the middle to intercept the communication and read the capability) in any way?

In the very nice tutorial, I could find some information about private keys on the server side, but no information about a server certificate (which in common TLS deployments has to be generated and signed and the signing authority needs to be present at the client to verify the chain of trust).

**Comment by talex5** [comment]
Yes, the capnp URL contains the fingerprint of the server's key. e.g.

> The sha-256:3Tj5y5Q2qpqN3Sbh0GRPxgORZw98_NtrU2nLI0-Tn6g part is the fingerprint of the server's public key. When the client connects, it uses this to verify that it is connected to the right server (not an imposter). Therefore, a Cap'n Proto vat does not need to be certified by a CA (and cannot be compromised by a rogue CA).

(from https://github.com/mirage/capnp-rpc#networking)

It only uses X.509 as a holder for the public key and does not use CAs or other information in the certificate (other schemes could be used though).

BTW, it seems a little tricky to get the client certificate from a new connection. Currently, I create a new TLS config for each incoming connection with its own "authenticator" that extracts the information:

https://github.com/mirage/capnp-rpc/blob/master/capnp-rpc-lwt/tls_wrapper.ml#L37

Is there a better way?

Also, did I get the end-of-file handling correct? It seemed a bit non-obvious, e.g. https://github.com/mirage/capnp-rpc/blob/master/capnp-rpc-lwt/tls_wrapper.ml#L16

**Comment by hannesm** [comment]
Thanks for your reply (and sorry for not reading carefully).  From an existing TLS session you can extract the epoch (in [Tls_lwt.Unix](http://mirleft.github.io/ocaml-tls/doc/Tls_lwt.Unix.html#VALepoch) or [Tls_mirage](http://mirleft.github.io/ocaml-tls/doc/Tls_mirage.Make.html#VALepoch)) (see https://github.com/hannesm/vmm/blob/bdedadf6897fd4c8584fcf1d23b4ca707194dbf3/app/vmmd.ml#L44-L48 as an example).  Its value is an instance of the record type [epoch_data](http://mirleft.github.io/ocaml-tls/doc/Core.html#TYPEepoch_data).

The end-of-file handling looks correct to me.  The reason is that a `read()` in TLS can lead to in-protocol messages (such as HelloRequest or ClientHello), which require more protocol messages -- and thus a `read()` may actually need to `write()` onto the connection -- which then can fail.   May be worth to document this properly - or translate the `` Error `Write `Closed `` into `` Ok `Eof ``.

**Comment by talex5** [comment]
Ah, great! I didn't know about the epoch function.

**Comment by hannesm** [comment]
do I understand this cap'n proto authentication correctly?  the hash of the server public key is embedded in the capibility?  and the client has to present a client certificate for the purpose of transmitting their public key to the server?  all other elements of the certificate do not matter (esp. subject / issuer / validity)!?

in this case, you need to provide some authenticator to `Config.server` (e.g. `null`) to have the server ask for a client certificate.  for the client side, the provided `server_key_fingerprint` authenticator accepts a (string * fp) list, and requires the certificate to contain the given name in its subject (or subject alternative name) - maybe we should add an authenticator which accepts only a single fingerprint, and does no checking of the name!?

**Comment by talex5** [comment]
Yes, that's right.

The client authentication part isn't actually needed if the "client" acts only as a client. However, it may be that the "server" also needs to connect to a capnp:// URL that happens to be hosted at the client. If the client proves ownership of a key when it connects to the server, then the server can reuse the same connection if it later needs to contact the client.

An authenticator that doesn't require a particular DN would be useful.
