### ISSUE TITLE
Error compiling persistent.capnp when installing

### ISSUE THREAD

**Issue by chrislomaxjones** [mirage/capnp-rpc#140]
I'm trying to install capnp-rpc-lwt (Ubuntu 14.04 with OCaml 4.04.0 and Opam 1.2.2) and seem to be running into an issue when using the command

`opam depext -i capnp-rpc-lwt`

the external dependencies seem to install fine but then there is an error when trying to compile capnp-rpc-lwt as shown below:

![image](https://user-images.githubusercontent.com/8000415/33684617-cd4174d8-dac6-11e7-9309-fb436b6e6e43.png)

Any advice would be really appreciated.

**Comment by talex5** [comment]
It wants a newer version of the `capnp` tool, I think.

However, we don't actually use the generics information here, so it might be possible to edit the file so that it works on older versions. Does it work if the file is just:

```
@0xb8630836983feed7;

interface Persistent@0xc8cb212fcd9f5691 {
  save @0 SaveParams -> SaveResults;

  struct SaveParams {
    sealFor @0 :AnyPointer;
  }
  struct SaveResults {
    sturdyRef @0 :AnyPointer;
  }
}

```

**Comment by talex5** [comment]
I've made this change now. You should be able to install with:

```
opam pin add capnp-rpc-lwt --dev-repo
```
