### ISSUE TITLE
[lwt, unix] Release supporting OCaml 4.06

### ISSUE THREAD

**Issue by jpdeplaix** [mirage/capnp-rpc#145]
Is there a release planned soon to support OCaml 4.06 for ```capnp-rpc-lwt``` and ```capnp-rpc-unix``` ?

**Comment by talex5** [comment]
I've submitted one at https://github.com/ocaml/opam-repository/pull/11206

**Comment by jpdeplaix** [comment]
Awesome, thx ! :)
