### ISSUE TITLE
Level 3

### ISSUE THREAD

**Issue by nickbetteridge** [mirage/capnp-rpc#199]
I have an use case where Bob needs to connect to Carol, but can only see Alice. I guess the only real solution is Level 3 here - I'm quite happy to have a stab at doing this but would be grateful for any kind of input as to the best way forward.

**Comment by talex5** [comment]
If Bob can't make a direct connection to Carol then you don't want level 3. Instead, you just want to proxy via Alice, which is what happens at the moment.

**Comment by nickbetteridge** [comment]
I'll give that a try - thanks
