### ISSUE TITLE
bind to ipv6 address

### ISSUE THREAD

**Issue by BChabanne** [mirage/capnp-rpc#278]
It seems that it is not possible for capnp-rpc server to bind to ipv6 addresses.

The error I get when serving such vat config
```
  let vat_config =Capnp_rpc_unix.Vat_config.create ~secret_key:(`File "/tmp/key") (`TCP ("::1", 7000))
```
is ` Failure("Unknown host \"::1\"")`

After searching a little bit, I found this related issue https://github.com/ocaml/ocaml/pull/13114 
It seems that the function `gethostbyname` is not supporting ipv6 but `getaddrinfo` does.

Would it make sense to use `getaddrinfo` in files `unix/network.ml` and `unix/capnp_rpc_unix.ml` ? instead of `gethostbyname` to support ipv6 ?

If ipv6 is to be supported, `Network.Location.of_string` would also need to be reworked a bit, because command line parsing would fail with
```
'--capnp-listen-address': PORT must be an integer
```

If there are no other big blockers you can think of, I can start to work on a PR to support ipv6

**Comment by talex5** [comment]
Fixed by #284 and #296.
